### ISSUE TITLE
ingame music

### ISSUE THREAD

**Issue by matthiashermsen** [matthiashermsen/sppro-gamejam-7#19]

**Comment by matthiashermsen** [comment]
https://onlinesequencer.net/1163936#139434

**Comment by matthiashermsen** [comment]
https://onlinesequencer.net/284364

**Comment by Indept-Studios** [comment]
https://freesound.org/people/julius_galla/sounds/193692/

**Comment by matthiashermsen** [comment]
done with https://github.com/matthiashermsen/sppro-gamejam-7/issues/18
