### ISSUE TITLE
game over music

### ISSUE THREAD

**Issue by matthiashermsen** [matthiashermsen/sppro-gamejam-7#20]

**Comment by Indept-Studios** [comment]
https://onlinesequencer.net/1158171

**Comment by Indept-Studios** [comment]
https://onlinesequencer.net/1163936

**Comment by matthiashermsen** [comment]
done with https://github.com/matthiashermsen/sppro-gamejam-7/issues/19

**Comment by matthiashermsen** [comment]
done with https://github.com/matthiashermsen/sppro-gamejam-7/issues/18
